### ISSUE TITLE
遇到错误

### ISSUE THREAD

**Issue by yuliuyu** [TheBobbyliu/Person-ReID#1]
你好，我在跑你的代码的时候，遇到了这个错误
AttributeError: 'Checkpoint' object has no attribute 'state'，请问如何解决，还有就是，我在git clone的时候，显示下载的文件大小是100多M，但是实际打开的时候只有十几M，这是怎么回事呢

![Screenshot from 2019-05-08 23-13-08](https://user-images.githubusercontent.com/44492204/57386564-301b7280-71e7-11e9-8502-5370a7becff4.png)

**Comment by yuliuyu** [comment]
你好，我是一名初学者，MGN,PCB+RPP的这两篇论文我都读过，最近跑了你的mgnrpp的模型和pcbrpp的模型，我知道RPP是用于精修的部分，但是你在mgnrpp的模型里似乎还没加入RPP的部分，那就相当于只用了mobilenet做的MGN是吗？在实际运行mgnrpp和pcbrpp这两个模型map的结果大概只有69%左右， 请问这是怎么回事呢，正常情况下，不是map的值都应该达到80%多吗？
[log.txt](https://github.com/TheBobbyliu/Person-ReID/files/3169106/log.txt)

mAP: 0.6944 rank1: 0.8711 rank3: 0.9338 rank5: 0.9516 rank10: 0.9700 (Best: 0.6944 @epoch 400)
mAP: 0.6798 rank1: 0.8575 rank3: 0.9308 rank5: 0.9483 rank10: 0.9718 (Best: 0.6829 @epoch 320)

**Comment by TheBobbyliu** [comment]
MGN requires the input size of images to be  (256,384), maybe you could try to revise config.txt.
There actually are implementation of RPP in mgnrpp.py. After training MGN for 400 epochs or so, set 'module' attibute in config to RPP, 'load' attribute to the latest checkpoint, 'epoch' to 200, and 'freeze' to 100, and train. Hope you can get what you want.

**Comment by yuliuyu** [comment]
first,train the  model "mgnrpp" or "mgn" only for 400 epohs?

**Comment by TheBobbyliu** [comment]
model: mgnrpp
module: MGN

**Comment by TheBobbyliu** [comment]
config.txt has been updated, you can reference from it now.

**Comment by yuliuyu** [comment]
thank you ,let me see

**Comment by txysq** [comment]
hi! I followed your instructions,Is that correct? but I had a problem. this is 'load' attribute that I had changed
# load&&save
load: home/lc/Desktop/Person-ReID-master/log/mgnrpp/checkpoint_400.pt
save: ./log/mgnrpp
restart:True

this  is the question that i had meet,How can I solve this problem?
lc@710:~/Desktop/Person-ReID-master$ python3 main.py --cfg config/config.txt
Loading model with unaccessible path!
[INFO] Making loss...
1.000 * CrossEntropy
2.000 * Triplet
No optimizer log loaded
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main(args)
  File "main.py", line 23, in main
    trainer_ = trainer.Trainer(args, model_, loss_, dataloader_, ckpt_, check_)
  File "/home/lc/Desktop/Person-ReID-master/trainer.py", line 34, in __init__
    self.ckpt.load(self)
  File "/home/lc/Desktop/Person-ReID-master/utils/checkpoint.py", line 93, in load
    if 'optimizer_state_dict' in self.state.keys():
AttributeError: 'Checkpoint' object has no attribute 'state'

**Comment by yuliuyu** [comment]
After I  "set model to mgnrpp/pcbrpp, module to MGN, train 400 epochs.",  when I want to train "RPP"part, I encountered the same error as above that "AttributeError: 'Checkpoint' object has no attribute 'state".

**Comment by TheBobbyliu** [comment]
check this feedback:
`Loading model with unaccessible path!`
which means that you entered an unaccessible path. 
Maybe change 
`home/lc/Desktop/Person-ReID-master/log/mgnrpp/checkpoint_400.pt`
to
`/home/lc/Desktop/Person-ReID-master/log/mgnrpp/checkpoint_400.pt`
would help

**Comment by yuliuyu** [comment]
I trained the "mgnrpp"model for two steps according to your instructions,but the result really makes me upset ,these are results that I had got:

[INFO] Epoch: 200	Learning rate: 2.00e-04
[INFO] [200/200]	24/24	[CrossEntropy: 0.3924][Triplet: 0.2198][Total: 0.6122]
[INFO] Test:
[INFO] mAP: 0.6898 rank1: 0.8795 rank3: 0.9436 rank5: 0.9555 rank10: 0.9739 (Best: 0.6898 @epoch 100)

and  It performs worse than the single "MGN" model.I remember that the single "MGN" model's map
is  about 70%

**Comment by yuliuyu** [comment]
I trained another time,the result remains almost the same.
[INFO] mAP: 0.6977 rank1: 0.8821 rank3: 0.9421 rank5: 0.9611 rank10: 0.9765 (Best: 0.6977 @epoch 100)

**Comment by yuliuyu** [comment]
when I train the "pcbrpp" model,I met the 
"  File "/home/lc/Desktop/Person-ReID/model/pcbrpp.py", line 19, in __init__
    super(MGN, self).__init__()
NameError: name 'MGN' is not defined " mistake,and I change the 'MGN' to 'PCBRPP',but I met another 
mistake
 " File "/home/lc/Desktop/Person-ReID/model/pcbrpp.py", line 109, in forward
    slice_results = self.mod(p2)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'PCBRPP' object has no attribute 'mod'"

**Comment by yuliuyu** [comment]
Sorry to bother you , I trained the "pcbrpp"model according your instructions,
and here the  result that I got 
"mAP: 0.6943 rank1: 0.8818 rank3: 0.9421 rank5: 0.9578 rank10: 0.9736 (Best: 0.6943 @epoch 100)" 
I don't why,but all the results that I got is almost same,no matter which model I  have ever tried and add "RPP" part or not.

**Comment by TheBobbyliu** [comment]
Sorry, I've been busy these days...
This piece of code is rewritten from the repository https://github.com/seathiefwang/MGN-pytorch, and I changed a lot of configurations during experimenting on other models, so maybe you can reference your parameters from this repository. I am also trying to reproduce what I have done(this is so awkward...), and there is a RPP loss function that I forgot to upload(I also forget if it works)... Anyway, I'll reproduce the results as soon as possible.

**Comment by TheBobbyliu** [comment]
I find the reason for the terrible results... It turns out that I use data augmentation so intensively that the model cannot fit training data well. Updates will be made in few minutes, or you can just edit  tran_transform_list in `data/__init__.py` to :
```
        train_transform_list = [
            transforms.Resize((args.height, args.width), interpolation=3),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ]
```

**Comment by yuliuyu** [comment]
hi,your test result  "MGN with p2=3&p3=4 | Market1501 | 0.8421 | 0.9365 | 0.9688 | 0.9771 | 0.9857" is the result of "mgnrpp" based on mobilenetV2  or   just  the result of  "mgn" based on resnet50,but sets the slice_p2 =3,  slice_p3 =4 ?

**Comment by TheBobbyliu** [comment]
The result is based on MobileNetV2.
